[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prace_core"
version = "0.1.0"
dependencies = [
    "click"
]

[project.scripts]
prace = "prace_core.cli:prace" 